channels:
  - conda-forge
  - bioconda
dependencies:
  - python = 3.7
  - numpy
  - scipy
  - flake8
  - pysam
  - piBigWig
  - py2bit
  - deeptoolsintervals
  - pytest
  - planemo
  - samtools
  - allure-python-commons==2.12.0
