channels:
  - conda-forge
  - bioconda
dependencies:
  - python = 3.11
  - numpy
  - scipy
  - flake8
  - pysam
  - deeptoolsintervals
  - pytest
  - planemo
  - samtools
  - allure-python-commons==2.12.0
  - pip
  - pip:
    - py2bit
    - pyBigWig
