name: Planemo
on: [push, pull_request]

env:
  GALAXY_BRANCH: release_22.05

defaults:
  run:
    shell: bash -l {0}

jobs:
  planemo_test:
    name: Planemo test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [1, 2, 3]
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@main
      with:
        environment-file: .github/env.yml
        cache-downloads: true
        environment-name: foo
        condarc: |
          channels:
            - conda-forge
            - bioconda
    - name: planemo
      run: |
        micromamba activate foo
        ./.planemo.sh ${{ matrix.chunk }} ${{ env.GALAXY_BRANCH }}
    - uses: actions/upload-artifact@v3
      with:
        name: 'Tool test output ${{ matrix.chunk }}'
        path: upload
  planemo_combine_outputs:
    name: Combine chunked test results
    needs: planemo_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_BRANCH }}
    - name: Combine outputs
      uses: galaxyproject/planemo-ci-action@v1
      id: combine
      with:
        mode: combine
        html-report: true
    - uses: actions/upload-artifact@v3
      with:
        name: 'All tool test results'
        path: upload
    - name: Check outputs
      uses: galaxyproject/planemo-ci-action@v1
      id: check
      with:
        mode: check