name: Test
on: [push, pull_request]
jobs:
  check_versions_matches:
    name: Check deeptools version matches galaxy tools
    runs-on: ubuntu-latest
    if: github.base_ref == 'master'
    steps:
    - uses: actions/checkout@v1
    - name: Check path
      run: find /home/runner/work/deepTools/deepTools -name "_version.py"
    - name: Get Version of Deeptools
      run: echo "deeptools_version=$(grep "__version__" /home/runner/work/deepTools/deepTools/deeptools/_version.py | awk '{print substr($NF, 2, length($NF) - 2)}')" >> $GITHUB_ENV
    - name: Get Version of Galaxy tools
      run: echo "galaxy_deeptools_version=$(grep "token.*TOOL_VERSION" /home/runner/work/deepTools/deepTools/galaxy/wrapper/deepTools_macros.xml | awk -F '>|<' '{print $3}')" >> $GITHUB_ENV
    - name: Versions
      run: | 
        echo deeptools version=${deeptools_version}
        echo deeptools version in galaxy=${galaxy_deeptools_version}
    - name: Fail PR if versions not matching
      run: |
        if [ -z $galaxy_deeptools_version ]; then
          echo "galaxy_deeptools_version not defined change the github action"
          exit 1
        fi
        if [ -z $deeptools_version ]; then
          echo "deeptools_version not defined change the github action"
          exit 1
        fi
        if [ "$galaxy_deeptools_version" != "$deeptools_version" ]; then
          echo "versions do not match"
          exit 1
        fi
  build-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: "dpryan79/github-actions/@master"
    - name: PEP8
      run: |
        source activate foo
        flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E722,W504,W605
    - name: Test deepTools
      run: |
        source activate foo
        nosetests --with-doctest -sv deeptools
    - name: make an artifact
      run: |
        source activate foo
        rm -f dist/*
        python setup.py sdist
    - uses: actions/upload-artifact@master
      with:
        name: "Dist files"
        path: "dist"
  build-osx:
    name: Test on OSX
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: "dpryan79/github-actions/@master"
    - name: Test deepTools
      run: |
        source activate foo
        nosetests --with-doctest -sv deeptools
